INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'CREATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (2, 'READ');
INSERT INTO AUTHORITY(ID, NAME) VALUES (3, 'UPDATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (4, 'DELETE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (5, 'ADMIN');
INSERT INTO AUTHORITY(ID, NAME) VALUES (8, 'GUEST');
INSERT INTO AUTHORITY(ID, NAME) VALUES (9, 'APP_ADMIN');