INSERT INTO TEAM(ID, NAME) VALUES (1, 'News');
INSERT INTO TEAM(ID, NAME) VALUES (2, 'Fun');
INSERT INTO TEAM(ID, NAME) VALUES (3, 'Movies');
INSERT INTO TEAM(ID, NAME) VALUES (4, 'Sports');
INSERT INTO TEAM(ID, NAME) VALUES (5, 'Television');
  
INSERT INTO USERS_TEAMS(USER_ID, TEAM_ID) VALUES (9, 4);
INSERT INTO USERS_TEAMS(USER_ID, TEAM_ID) VALUES (10, 4);
INSERT INTO USERS_TEAMS(USER_ID, TEAM_ID) VALUES (11, 4);
INSERT INTO USERS_TEAMS(USER_ID, TEAM_ID) VALUES (12, 4);
INSERT INTO USERS_TEAMS(USER_ID, TEAM_ID) VALUES (13, 2);
INSERT INTO USERS_TEAMS(USER_ID, TEAM_ID) VALUES (14, 2);
INSERT INTO USERS_TEAMS(USER_ID, TEAM_ID) VALUES (15, 2);

INSERT INTO USERS_TEAMS(USER_ID, TEAM_ID) VALUES (9, 3);
INSERT INTO USERS_TEAMS(USER_ID, TEAM_ID) VALUES (10, 3);
INSERT INTO USERS_TEAMS(USER_ID, TEAM_ID) VALUES (11, 3);
INSERT INTO USERS_TEAMS(USER_ID, TEAM_ID) VALUES (12, 3);


INSERT INTO TEAM_AUTHORITIES(TEAM_ID, AUTHORITY_ID) VALUES (3, 2);
INSERT INTO TEAM_AUTHORITIES(TEAM_ID, AUTHORITY_ID) VALUES (3, 3);

INSERT INTO TEAM_AUTHORITIES(TEAM_ID, AUTHORITY_ID) VALUES (4, 2);
INSERT INTO TEAM_AUTHORITIES(TEAM_ID, AUTHORITY_ID) VALUES (4, 3);
