CREATE TABLE TEMP_USER (
  ID BIGINT NOT NULL  AUTO_INCREMENT,
  PASSWORD VARCHAR(255),
  USER_NAME VARCHAR(255),
  ACCOUNT_EXPIRED BOOLEAN,
  ACCOUNT_LOCKED BOOLEAN,
  CREDENTIALS_EXPIRED BOOLEAN,
  ENABLED BOOLEAN,
  PRIMARY KEY (ID)
);

ALTER TABLE TEMP_USER ADD CONSTRAINT TEMP_USER_USER_NAME UNIQUE(USER_NAME);

CREATE TABLE TEMP_USERS_AUTHORITIES (
   USER_ID BIGINT NOT NULL,
   AUTHORITY_ID BIGINT NOT NULL,
   PRIMARY KEY (USER_ID, AUTHORITY_ID)
);

ALTER TABLE TEMP_USERS_AUTHORITIES ADD CONSTRAINT TEMP_USERS_AUTHORITIES_AUTHORITY
   FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY;

ALTER TABLE TEMP_USERS_AUTHORITIES ADD CONSTRAINT TEMP_USERS_AUTHORITIES_TEMP_USER
   FOREIGN KEY (USER_ID) REFERENCES TEMP_USER;