CREATE TABLE USER_INFO (
  USER_ID BIGINT NOT NULL,
  FIRST_NAME VARCHAR(16),
  LAST_NAME VARCHAR(16),
  ADDRESS VARCHAR(255),
  PRIMARY KEY (USER_ID)
);

ALTER TABLE USER_INFO ADD CONSTRAINT USER_INFO_USER_
   FOREIGN KEY (USER_ID) REFERENCES USER_;