INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, ADDRESS) VALUES (1, 'Subhash', 'Bose', 'India');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, ADDRESS) VALUES (2, 'Bhagat', 'Singh', 'India');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, ADDRESS) VALUES (3, 'Laxmi', 'Sahgal', 'India');

INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, ADDRESS) VALUES (9, 'Adolf', 'Hitler', 'Germany');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, ADDRESS) VALUES (10, 'Rani', 'Laxmibai', 'India');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, ADDRESS) VALUES (11, 'Joseph', 'Stalin', 'Russia');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, ADDRESS) VALUES (12, 'Benito', 'Mussolini', 'Italy');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, ADDRESS) VALUES (13, 'Sukhdev', 'Thapar', 'India');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, ADDRESS) VALUES (14, 'Rajguru', 'Shivaram', 'India');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, ADDRESS) VALUES (15, 'Mangal', 'Pandey', 'India');
