INSERT INTO STUDENT(ID, NAME) VALUES (1, 'Lina');
INSERT INTO STUDENT(ID, NAME) VALUES (2, 'Deepak');
INSERT INTO STUDENT(ID, NAME) VALUES (3, 'Lakshmi');
INSERT INTO STUDENT(ID, NAME) VALUES (4, 'Survi');
INSERT INTO STUDENT(ID, NAME) VALUES (5, 'Ajay');


